pipeline {
    agent any

    stages {
                stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }    

stage('Check Node.js and npm Versions') {
    steps {
        sh 'node -v'
        sh 'npm -v'
    }
}


        
    }
}
