pipeline {
    agent any

    stages {
                stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }    


        stage('npm install') {
            steps {
                sh 'npm install'
            }
        }


        
    }
}
