pipeline {
    agent any

    stages {
                stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }    

stage('Install Node.js and npm') {
    steps {
        sh 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash'
        sh 'source ~/.nvm/nvm.sh'
        sh 'nvm install node'
    }
}



        
    }
}
